In [5]:
import numpy as np 
a=np.array([[2,3],[5,2]])
print(a)

[[2 3]
 [5 2]]


In [11]:
d=np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
print(d)
print(d.shape) #배열 d의 크기 : 리스트 3개에 각 5개씩 원소를 가지고 있음.
print(d.dtype) #배열의 타입

[[1 2 3 4 5]
 [2 4 5 6 7]
 [5 7 8 9 9]]
(3, 5)
int32


In [20]:
arr1=np.array([[2,3,4],[6,7,8]])
arr2=np.array([[12,23,14],[36,47,58]])
print("더하기", arr1+arr2)
print("곱하기",arr1*arr2)
print("나누기",arr1/arr2)

더하기 [[14 26 18]
 [42 54 66]]
곱하기 [[ 24  69  56]
 [216 329 464]]
나누기 [[0.16666667 0.13043478 0.28571429]
 [0.16666667 0.14893617 0.13793103]]


In [21]:
arr1=np.array([[2,3,4],[6,7,8]])
arr3=np.array([100,200,300]) #177p 서로 다른 크기의 배열을 연산하는 기능을 브로드캐스팅기능이라고 함.
print(arr1+arr3)

[[102 203 304]
 [106 207 308]]


In [22]:
arr1=np.array([[2,3,4],[6,7,8]])
arr4=np.array([1,2,3,4,5,6,7,8,9,10]) #행과 열의 크기가 모두 다 다른 매열은 더할 수 없습니다.
print(arr1+arr4)

ValueError: operands could not be broadcast together with shapes (2,3) (10,) 

In [23]:
arr1=np.array([[2,3,4],[6,7,8]])
arr5=np.array([[9],[3]])
print(arr1+arr5)

[[11 12 13]
 [ 9 10 11]]


In [26]:
arr4=np.arange(10)
print(arr4)
print(arr4[:4])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]


In [30]:
print(arr1)
print(arr1[1,2]) #arr1리스트에서 1행 2열의 원소를 출력
print(arr1[:,2]) #arr1리스트에서 모든 행의 2열 원소를 출력

[[2 3 4]
 [6 7 8]]
8
[4 8]
