In [1]:
import os, usecsv
import numpy as np
quest=np.array(usecsv.switch(usecsv.opencsv('quest.csv')))
quest


array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 6., 2., 5.],
       [3., 6., 4., 2., 5.],
       [3., 5., 4., 1., 6.],
       [3., 5., 5., 1., 3.]])

In [2]:
quest>5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [3]:
quest[quest>5]

array([6., 6., 6.])

In [4]:
quest[quest>5]=5

In [5]:
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 5., 2., 5.],
       [3., 5., 4., 2., 5.],
       [3., 5., 4., 1., 5.],
       [3., 5., 5., 1., 3.]])

In [6]:
usecsv.writecsv('resultcsv.csv',list(quest))